# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cryptoMP.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(882, 453)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/mplog_mini.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 140, 211, 261))
        self.frame.setStyleSheet("#frame{border-image: url(:/icons/icons/anasayfa.png);}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(16, 169, 181, 25))
        self.label.setStyleSheet("#label{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(16, 210, 181, 25))
        self.label_2.setStyleSheet("#label_2{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(35, 10, 141, 141))
        self.frame_5.setStyleSheet("border-image: url(:/icons/icons/btc.png);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(230, 140, 211, 261))
        self.frame_2.setStyleSheet("#frame_2{border-image: url(:/icons/icons/anasayfa.png);}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(16, 170, 181, 25))
        self.label_3.setStyleSheet("#label_3{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(16, 210, 181, 25))
        self.label_4.setStyleSheet("#label_4{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(35, 10, 141, 141))
        self.frame_6.setStyleSheet("border-image: url(:/icons/icons/eth.png);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(440, 140, 211, 261))
        self.frame_3.setStyleSheet("#frame_3{border-image: url(:/icons/icons/anasayfa.png);}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(16, 170, 181, 25))
        self.label_5.setStyleSheet("#label_5{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(16, 210, 181, 25))
        self.label_6.setStyleSheet("#label_6{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(35, 10, 141, 141))
        self.frame_7.setStyleSheet("border-image: url(:/icons/icons/doge.png);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(650, 140, 211, 261))
        self.frame_4.setStyleSheet("#frame_4{border-image: url(:/icons/icons/anasayfa.png);}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(16, 170, 181, 25))
        self.label_7.setStyleSheet("#label_7{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_7.setText("")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(16, 210, 181, 25))
        self.label_8.setStyleSheet("#label_8{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(62, 62, 62);\n"
"border-radius:10px;\n"
"\n"
"\n"
"}")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setGeometry(QtCore.QRect(35, 10, 141, 141))
        self.frame_8.setStyleSheet("border-image: url(:/icons/icons/xrp.png);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.centralwidget)
        self.frame_9.setGeometry(QtCore.QRect(10, 0, 871, 401))
        self.frame_9.setStyleSheet("image: url(:/icons/icons/aa.png);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_9.raise_()
        self.frame.raise_()
        self.frame_2.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kripto Para Takip || Maresal PRM"))
import icons_rc
