# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'networking.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(555, 320)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 100, 531, 141))
        self.textBrowser.setObjectName("textBrowser")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(430, 0, 111, 101))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(50, 30, 241, 41))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 30, 211, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 541, 231))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.textBrowser.raise_()
        self.frame.raise_()
        self.progressBar.raise_()
        self.lineEdit.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 555, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNetworkipList = QtWidgets.QAction(MainWindow)
        self.actionNetworkipList.setObjectName("actionNetworkipList")
        self.actionOpenPorts = QtWidgets.QAction(MainWindow)
        self.actionOpenPorts.setObjectName("actionOpenPorts")
        self.actionPinging = QtWidgets.QAction(MainWindow)
        self.actionPinging.setObjectName("actionPinging")
        self.actionmaresalp = QtWidgets.QAction(MainWindow)
        self.actionmaresalp.setObjectName("actionmaresalp")
        self.toolBar.addAction(self.actionNetworkipList)
        self.toolBar.addAction(self.actionOpenPorts)
        self.toolBar.addAction(self.actionPinging)
        self.toolBar.addAction(self.actionmaresalp)

        self.actionOpenPorts.setIcon(QtGui.QIcon("icons/port.png"))
        self.actionPinging.setIcon(QtGui.QIcon("icons/ping.png")) 
        self.frame.setStyleSheet("image:url(icons/network.png);")
        self.lineEdit.setHidden(True)
        self.progressBar.setHidden(True)
        self.actionNetworkipList.setIcon(QtGui.QIcon("icons/ethernet.png"))
        self.toolBar.setIconSize(QtCore.QSize(80,38))
        self.actionmaresalp.setIcon(QtGui.QIcon("icons/marelogo.ico"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Network Details | Maresal PRM"))
        self.label.setText(_translate("MainWindow", "Details"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNetworkipList.setText(_translate("MainWindow", "Network Ip List"))
        self.actionOpenPorts.setText(_translate("MainWindow", "Open Ports"))
        self.actionPinging.setText(_translate("MainWindow", "Pinging"))
        self.actionmaresalp.setText(_translate("MainWindow", "maresalp"))
